In [169]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler, RobustScaler

In [170]:
los_cleaned_df=pd.read_csv('Length_cleaned.csv', index_col=False)
los_cleaned_df.drop(columns='respiration', inplace=True)
los_cleaned_df

,eid,rcount,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,...,neutrophils,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,secondarydiagnosisnonicd9,facid,lengthofstay
0,1,0,F,0,0,0,0,0,0,0,...,14200.0,140.361132,192.476918,12.0,1.390722,30.432418,96,4,B,3
1,2,5,F,0,0,0,0,0,0,0,...,4100.0,136.731692,94.078507,8.0,0.943164,28.460516,61,1,A,7
2,3,1,F,0,0,0,0,0,0,0,...,8900.0,133.058514,130.530524,12.0,1.065750,28.843812,64,2,B,3
3,4,0,F,0,0,0,0,0,0,0,...,9400.0,138.994023,163.377028,12.0,0.906862,27.959007,76,1,A,1
4,5,0,F,0,0,0,1,0,1,0,...,9050.0,138.634836,94.886654,11.5,1.242854,30.258927,67,2,E,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99864,99996,3,M,0,0,0,0,0,0,0,...,9300.0,132.614977,171.422555,12.0,0.650323,30.063069,80,1,B,6
99865,99997,0,M,0,0,0,0,0,0,0,...,9300.0,138.327320,122.342450,12.0,1.521424,28.969548,61,1,B,1
99866,99998,1,M,0,0,1,0,0,0,0,...,7700.0,136.695905,108.288106,12.0,1.025677,26.354919,61,1,C,4
99867,99999,0,M,0,0,0,0,0,0,1,...,8200.0,135.980516,111.750731,16.0,1.035400,29.193462,59,1,B,4
99868,100000,0,F,0,0,0,0,0,0,0,...,14200.0,140.950137,149.572205,12.0,0.813004,25.175760,74,4,B,2

In [171]:
#X=los_cleaned_df.drop(columns=['lengthofstay'])
#y=los_cleaned_df['lengthofstay']

In [172]:
#X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=23, test_size=0.33)

#### Encoding categorical columns

##### Gender M/F

In [173]:
los_cleaned_df['gender']

0        F
1        F
2        F
3        F
4        F
        ..
99864    M
99865    M
99866    M
99867    M
99868    F
Name: gender, Length: 99869, dtype: object

In [174]:
enc=OneHotEncoder(handle_unknown='ignore', sparse_output=False, drop='first').set_output(transform='pandas')
enc_transform=enc.fit_transform(los_cleaned_df[['gender']])
enc_transform

       gender_M
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
...         ...
99864       1.0
99865       1.0
99866       1.0
99867       1.0
99868       0.0

[99869 rows x 1 columns]

In [175]:
los_cleaned_df=pd.concat([los_cleaned_df, enc_transform], axis=1).drop(columns=['gender'])

In [176]:
los_cleaned_df

,eid,rcount,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,...,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,secondarydiagnosisnonicd9,facid,lengthofstay,gender_M
0,1,0,0,0,0,0,0,0,0,0,...,140.361132,192.476918,12.0,1.390722,30.432418,96,4,B,3,0.0
1,2,5,0,0,0,0,0,0,0,0,...,136.731692,94.078507,8.0,0.943164,28.460516,61,1,A,7,0.0
2,3,1,0,0,0,0,0,0,0,0,...,133.058514,130.530524,12.0,1.065750,28.843812,64,2,B,3,0.0
3,4,0,0,0,0,0,0,0,0,0,...,138.994023,163.377028,12.0,0.906862,27.959007,76,1,A,1,0.0
4,5,0,0,0,0,1,0,1,0,0,...,138.634836,94.886654,11.5,1.242854,30.258927,67,2,E,4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99864,99996,3,0,0,0,0,0,0,0,0,...,132.614977,171.422555,12.0,0.650323,30.063069,80,1,B,6,1.0
99865,99997,0,0,0,0,0,0,0,0,0,...,138.327320,122.342450,12.0,1.521424,28.969548,61,1,B,1,1.0
99866,99998,1,0,0,1,0,0,0,0,0,...,136.695905,108.288106,12.0,1.025677,26.354919,61,1,C,4,1.0
99867,99999,0,0,0,0,0,0,0,1,0,...,135.980516,111.750731,16.0,1.035400,29.193462,59,1,B,4,1.0
99868,100000,0,0,0,0,0,0,0,0,0,...,140.950137,149.572205,12.0,0.813004,25.175760,74,4,B,2,0.0

#### Facility ID
##### Since this is a synthetic dataset, i made sure the facility column wasnt just randomly assigned values without different LOS values. Since the values are different we can find a pattern.

In [177]:
los_cleaned_df.groupby('facid')['lengthofstay'].mean()

facid
A    3.269475
B    3.282928
C    4.889789
D    4.816450
E    5.154949
Name: lengthofstay, dtype: float64

In [178]:
enc_transform=enc.fit_transform(los_cleaned_df[['facid']])
enc_transform

       facid_B  facid_C  facid_D  facid_E
0          1.0      0.0      0.0      0.0
1          0.0      0.0      0.0      0.0
2          1.0      0.0      0.0      0.0
3          0.0      0.0      0.0      0.0
4          0.0      0.0      0.0      1.0
...        ...      ...      ...      ...
99864      1.0      0.0      0.0      0.0
99865      1.0      0.0      0.0      0.0
99866      0.0      1.0      0.0      0.0
99867      1.0      0.0      0.0      0.0
99868      1.0      0.0      0.0      0.0

[99869 rows x 4 columns]

In [179]:
los_cleaned_df=pd.concat([los_cleaned_df, enc_transform], axis=1).drop(columns=['facid'])

In [180]:
los_cleaned_df

,eid,rcount,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,...,creatinine,bmi,pulse,secondarydiagnosisnonicd9,lengthofstay,gender_M,facid_B,facid_C,facid_D,facid_E
0,1,0,0,0,0,0,0,0,0,0,...,1.390722,30.432418,96,4,3,0.0,1.0,0.0,0.0,0.0
1,2,5,0,0,0,0,0,0,0,0,...,0.943164,28.460516,61,1,7,0.0,0.0,0.0,0.0,0.0
2,3,1,0,0,0,0,0,0,0,0,...,1.065750,28.843812,64,2,3,0.0,1.0,0.0,0.0,0.0
3,4,0,0,0,0,0,0,0,0,0,...,0.906862,27.959007,76,1,1,0.0,0.0,0.0,0.0,0.0
4,5,0,0,0,0,1,0,1,0,0,...,1.242854,30.258927,67,2,4,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99864,99996,3,0,0,0,0,0,0,0,0,...,0.650323,30.063069,80,1,6,1.0,1.0,0.0,0.0,0.0
99865,99997,0,0,0,0,0,0,0,0,0,...,1.521424,28.969548,61,1,1,1.0,1.0,0.0,0.0,0.0
99866,99998,1,0,0,1,0,0,0,0,0,...,1.025677,26.354919,61,1,4,1.0,0.0,1.0,0.0,0.0
99867,99999,0,0,0,0,0,0,0,1,0,...,1.035400,29.193462,59,1,4,1.0,1.0,0.0,0.0,0.0
99868,100000,0,0,0,0,0,0,0,0,0,...,0.813004,25.175760,74,4,2,0.0,1.0,0.0,0.0,0.0

In [181]:
los_cleaned_df.columns

Index(['eid', 'rcount', 'dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition', 'hemo', 'hematocrit',
       'neutrophils', 'sodium', 'glucose', 'bloodureanitro', 'creatinine',
       'bmi', 'pulse', 'secondarydiagnosisnonicd9', 'lengthofstay', 'gender_M',
       'facid_B', 'facid_C', 'facid_D', 'facid_E'],
      dtype='object')

In [182]:
X=los_cleaned_df.drop(columns=['lengthofstay'])
y=los_cleaned_df['lengthofstay']
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=23, test_size=0.33)

#### Standardizing numerical columns

##### Reading the Scikit learn documentation for different scalers that can be used, standard scaler which is the most commonly used scaler, is effected by outliers. Since i have decided to keep outliers for BUN and neutrophils, i have used the ROBUST SCALER.

In [183]:
numerics=['bloodureanitro', 'creatinine', 'bmi', 'pulse', 'sodium', 'glucose', 'hematocrit', 'neutrophils']
# df with the numerical values only. 
X_train_numerical=X_train[numerics]
X_test_numerical=X_test[numerics]

# drop the orignal columns since we will eventually concatenate the scaled version of these columns 
X_train.drop(columns=['bloodureanitro', 'creatinine', 'bmi', 'pulse', 'sodium', 'glucose', 'hematocrit', 'neutrophils', 'eid'], inplace=True)
X_test.drop(columns=['bloodureanitro', 'creatinine', 'bmi', 'pulse', 'sodium', 'glucose', 'hematocrit', 'neutrophils', 'eid'], inplace=True)

In [184]:
X_train.columns

Index(['rcount', 'dialysisrenalendstage', 'asthma', 'irondef', 'pneum',
       'substancedependence', 'psychologicaldisordermajor', 'depress',
       'psychother', 'fibrosisandother', 'malnutrition', 'hemo',
       'secondarydiagnosisnonicd9', 'gender_M', 'facid_B', 'facid_C',
       'facid_D', 'facid_E'],
      dtype='object')

In [185]:
print(X_train_numerical.columns)
print(X_test_numerical.columns)

Index(['bloodureanitro', 'creatinine', 'bmi', 'pulse', 'sodium', 'glucose',
       'hematocrit', 'neutrophils'],
      dtype='object')
Index(['bloodureanitro', 'creatinine', 'bmi', 'pulse', 'sodium', 'glucose',
       'hematocrit', 'neutrophils'],
      dtype='object')

In [186]:
scaler=RobustScaler()
# the scalers math is based on the training set only, which is why we use fit only on the training set and not on the test set. 
# numpy array with the scaled values. 
X_train_scaled=(scaler.fit_transform(X_train_numerical))
X_test_scaled=scaler.transform(X_test_numerical)

X_train_scaled_df=pd.DataFrame(X_train_scaled, columns=['bloodureanitro', 'creatinine', 'bmi', 'pulse', 'sodium', 'glucose','hematocrit', 'neutrophils'], index=X_train_numerical.index)
X_test_scaled_df=pd.DataFrame(X_test_scaled, columns=['bloodureanitro', 'creatinine', 'bmi', 'pulse', 'sodium', 'glucose','hematocrit', 'neutrophils'], index=X_test_numerical.index)

In [187]:
X_train=pd.concat([X_train, X_train_scaled_df ], axis=1, ignore_index=False)
X_test=pd.concat([X_test, X_test_scaled_df], axis=1)

In [188]:
X_train.head()

,rcount,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,fibrosisandother,...,facid_D,facid_E,bloodureanitro,creatinine,bmi,pulse,sodium,glucose,hematocrit,neutrophils
24314,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,1.333333,-1.083114,0.611292,0.400000,0.323644,-0.759409,-0.25,-1.351351
74634,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000000,0.494035,0.585992,1.333333,-0.078842,-0.762456,0.00,0.000000
67035,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000000,0.515914,0.131959,-0.066667,0.387946,-0.583580,0.00,0.000000
58507,3,1,0,0,1,0,1,0,1,0,...,0.0,1.0,12.333333,0.826010,0.163295,-0.733333,-0.939186,-0.052477,0.60,-0.351351
61823,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000000,0.890477,-0.853016,0.133333,-0.803162,-0.935081,0.00,0.000000

In [189]:
X_test.head()

,rcount,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,fibrosisandother,...,facid_D,facid_E,bloodureanitro,creatinine,bmi,pulse,sodium,glucose,hematocrit,neutrophils
28364,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000000,-1.748015,-0.370825,-0.066667,-0.845936,0.543135,0.00,0.000000
52104,1,0,0,0,0,0,0,0,0,0,...,0.0,0.0,-0.666667,-0.742097,-0.437589,0.933333,0.310311,-0.663427,0.40,-0.324324
41564,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000000,-0.142735,0.785421,-0.466667,-0.302259,0.543083,-0.60,0.702703
90602,2,0,0,0,0,0,0,0,0,0,...,0.0,0.0,2.666667,-0.326120,1.298190,1.066667,-0.416031,-0.022966,1.75,0.918919
53808,0,0,0,0,0,1,0,0,0,0,...,0.0,1.0,-2.000000,-0.199409,0.886259,-0.666667,0.025963,0.347646,-2.00,0.729730

In [190]:
# since we have updated our train, test dataframes with the scaled values, we can import them as csv to our modelling notebook. 
X_train.to_csv('X_train.csv', index=False )
X_test.to_csv('X_test.csv', index=False )
y_train.to_csv('y_train.csv', index=False )
y_test.to_csv('y_test.csv', index=False )