In [117]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [118]:
los_cleaned_df=pd.read_csv('Length_cleaned.csv', index_col=False)
los_cleaned_df

,eid,rcount,gender,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,...,sodium,glucose,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,facid,lengthofstay
0,1,0,F,0,0,0,0,0,0,0,...,140.361132,192.476918,12.0,1.390722,30.432418,96,6.5,4,B,3
1,2,5,F,0,0,0,0,0,0,0,...,136.731692,94.078507,8.0,0.943164,28.460516,61,6.5,1,A,7
2,3,1,F,0,0,0,0,0,0,0,...,133.058514,130.530524,12.0,1.065750,28.843812,64,6.5,2,B,3
3,4,0,F,0,0,0,0,0,0,0,...,138.994023,163.377028,12.0,0.906862,27.959007,76,6.5,1,A,1
4,5,0,F,0,0,0,1,0,1,0,...,138.634836,94.886654,11.5,1.242854,30.258927,67,5.6,2,E,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99864,99996,3,M,0,0,0,0,0,0,0,...,132.614977,171.422555,12.0,0.650323,30.063069,80,6.5,1,B,6
99865,99997,0,M,0,0,0,0,0,0,0,...,138.327320,122.342450,12.0,1.521424,28.969548,61,6.5,1,B,1
99866,99998,1,M,0,0,1,0,0,0,0,...,136.695905,108.288106,12.0,1.025677,26.354919,61,6.9,1,C,4
99867,99999,0,M,0,0,0,0,0,0,1,...,135.980516,111.750731,16.0,1.035400,29.193462,59,5.6,1,B,4
99868,100000,0,F,0,0,0,0,0,0,0,...,140.950137,149.572205,12.0,0.813004,25.175760,74,6.5,4,B,2

In [119]:
X=los_cleaned_df.drop(columns=['lengthofstay'])
y=los_cleaned_df['lengthofstay']

In [120]:
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=23, test_size=0.33)

#### Encoding categorical columns

##### Gender M/F

In [121]:
los_cleaned_df['gender']

0        F
1        F
2        F
3        F
4        F
        ..
99864    M
99865    M
99866    M
99867    M
99868    F
Name: gender, Length: 99869, dtype: object

In [122]:
enc=OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform='pandas')
enc_transform=enc.fit_transform(los_cleaned_df[['gender']])
enc_transform

       gender_F  gender_M
0           1.0       0.0
1           1.0       0.0
2           1.0       0.0
3           1.0       0.0
4           1.0       0.0
...         ...       ...
99864       0.0       1.0
99865       0.0       1.0
99866       0.0       1.0
99867       0.0       1.0
99868       1.0       0.0

[99869 rows x 2 columns]

In [123]:
los_cleaned_df=pd.concat([los_cleaned_df, enc_transform], axis=1).drop(columns=['gender'])

In [124]:
los_cleaned_df

,eid,rcount,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,...,bloodureanitro,creatinine,bmi,pulse,respiration,secondarydiagnosisnonicd9,facid,lengthofstay,gender_F,gender_M
0,1,0,0,0,0,0,0,0,0,0,...,12.0,1.390722,30.432418,96,6.5,4,B,3,1.0,0.0
1,2,5,0,0,0,0,0,0,0,0,...,8.0,0.943164,28.460516,61,6.5,1,A,7,1.0,0.0
2,3,1,0,0,0,0,0,0,0,0,...,12.0,1.065750,28.843812,64,6.5,2,B,3,1.0,0.0
3,4,0,0,0,0,0,0,0,0,0,...,12.0,0.906862,27.959007,76,6.5,1,A,1,1.0,0.0
4,5,0,0,0,0,1,0,1,0,0,...,11.5,1.242854,30.258927,67,5.6,2,E,4,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99864,99996,3,0,0,0,0,0,0,0,0,...,12.0,0.650323,30.063069,80,6.5,1,B,6,0.0,1.0
99865,99997,0,0,0,0,0,0,0,0,0,...,12.0,1.521424,28.969548,61,6.5,1,B,1,0.0,1.0
99866,99998,1,0,0,1,0,0,0,0,0,...,12.0,1.025677,26.354919,61,6.9,1,C,4,0.0,1.0
99867,99999,0,0,0,0,0,0,0,1,0,...,16.0,1.035400,29.193462,59,5.6,1,B,4,0.0,1.0
99868,100000,0,0,0,0,0,0,0,0,0,...,12.0,0.813004,25.175760,74,6.5,4,B,2,1.0,0.0

##### Facility ID
###### Since this is a synthetic dataset, i made sure the facility column wasnt just randomly assigned values without different LOS values. Since the values are different we can find a pattern.

In [125]:
los_cleaned_df.groupby('facid')['lengthofstay'].mean()

facid
A    3.269475
B    3.282928
C    4.889789
D    4.816450
E    5.154949
Name: lengthofstay, dtype: float64

In [126]:
enc_transform=enc.fit_transform(los_cleaned_df[['facid']])
enc_transform

       facid_A  facid_B  facid_C  facid_D  facid_E
0          0.0      1.0      0.0      0.0      0.0
1          1.0      0.0      0.0      0.0      0.0
2          0.0      1.0      0.0      0.0      0.0
3          1.0      0.0      0.0      0.0      0.0
4          0.0      0.0      0.0      0.0      1.0
...        ...      ...      ...      ...      ...
99864      0.0      1.0      0.0      0.0      0.0
99865      0.0      1.0      0.0      0.0      0.0
99866      0.0      0.0      1.0      0.0      0.0
99867      0.0      1.0      0.0      0.0      0.0
99868      0.0      1.0      0.0      0.0      0.0

[99869 rows x 5 columns]

In [127]:
los_cleaned_df=pd.concat([los_cleaned_df, enc_transform], axis=1).drop(columns=['facid'])

In [128]:
los_cleaned_df

,eid,rcount,dialysisrenalendstage,asthma,irondef,pneum,substancedependence,psychologicaldisordermajor,depress,psychother,...,respiration,secondarydiagnosisnonicd9,lengthofstay,gender_F,gender_M,facid_A,facid_B,facid_C,facid_D,facid_E
0,1,0,0,0,0,0,0,0,0,0,...,6.5,4,3,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2,5,0,0,0,0,0,0,0,0,...,6.5,1,7,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,3,1,0,0,0,0,0,0,0,0,...,6.5,2,3,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,4,0,0,0,0,0,0,0,0,0,...,6.5,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5,0,0,0,0,1,0,1,0,0,...,5.6,2,4,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99864,99996,3,0,0,0,0,0,0,0,0,...,6.5,1,6,0.0,1.0,0.0,1.0,0.0,0.0,0.0
99865,99997,0,0,0,0,0,0,0,0,0,...,6.5,1,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0
99866,99998,1,0,0,1,0,0,0,0,0,...,6.9,1,4,0.0,1.0,0.0,0.0,1.0,0.0,0.0
99867,99999,0,0,0,0,0,0,0,1,0,...,5.6,1,4,0.0,1.0,0.0,1.0,0.0,0.0,0.0
99868,100000,0,0,0,0,0,0,0,0,0,...,6.5,4,2,1.0,0.0,0.0,1.0,0.0,0.0,0.0